#
# Copyright (C) 2024 Jan Nowotsch
# Author Jan Nowotsch	<jan.nowotsch@gmail.com>
#
# Released under the terms of the GNU GPL v2.0
#



bin-y := dtsls

dtsls-y := \
	main.o \
	config.o \
	lsp.o \
	lsp/ \
	parser/ \
	utils/

dtsls-ldlibs := -ljson-c
